dist: bionic
language: minimal
addons:
  apt:
    packages:
    - build-essential
    - git
    - cmake
    - wget
    - vim
    - lsb-release
    - software-properties-common
    - zlib1g-dev
    - openjdk-11-jre
    - python3
    - python3-pip
    - python3-setuptools
    - python3-psutil
  sonarcloud:
    organization: "ftsrg"
env:
- THETA_VERSION="v1.2.0"
script:
  # fetch LLVM and other dependencies
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
  - sudo apt-get update
  - sudo add-apt-repository ppa:mhier/libboost-latest -y
  - sudo apt-get update
  - sudo apt-get install -y clang-9 llvm-9-dev llvm-9-tools llvm-9-runtime libboost1.70-dev
  - sudo ln -s `which clang-9` /usr/bin/clang
  - sudo ln -s `which llvm-link-9` /usr/bin/llvm-link -f
  - sudo ln -s `which opt-9` /usr/bin/opt -f
  - sudo ln -s `which FileCheck-9` /usr/bin/FileCheck
  - sudo pip3 install lit
  # create build folder
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=clang++-9 -DGAZER_ENABLE_UNIT_TESTS=On -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
  - cd ..
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  # run unit tests
  - cmake --build build --target check-unit
  # download theta (and related libs) to gazer subdirectory
  - mkdir -p build/tools/gazer-theta/theta
  - mkdir -p build/tools/gazer-theta/theta/lib
  - wget "https://github.com/ftsrg/theta/releases/download/$THETA_VERSION/theta-cfa-cli.jar" -O build/tools/gazer-theta/theta/theta-cfa-cli.jar
  - wget "https://github.com/ftsrg/theta/raw/$THETA_VERSION/lib/libz3.so" -P build/tools/gazer-theta/theta/lib/
  - wget "https://github.com/ftsrg/theta/raw/$THETA_VERSION/lib/libz3java.so" -P build/tools/gazer-theta/theta/lib/
  # run integration test suite
  - cmake --build build --target check-functional
  # run SonarCloud analysis
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output || true

notifications:
  email:
    on_success: change
    on_failure: always
